[project]
name = "py-fast-ires"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.0",
    "scipy>=1.15.3",
]
